sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: n6oLuNcxmIp0QrTQI6OS223TeT4ZH5OoPIivCoTCcQNbK2CQ5ebqtU7JEzE65Mzm7N6ZeAzYIxAYnc5Sb7uFzpT1FgwzhX9W9Gehaudm8dSW5e0frbtSqfxmVD7rtwqfCqXJTgRfTHM49i0FJjp6U51p3LwVgRtCDodniycgoZ8pLooYCTQlkpou0TTeibZaIoO0jUK/QvK3UcwxhmaetpB0X6Q18s/iGrnwVJfK7xhY5do4gi7i84AXrJQ/SOckPDBbitZ5IAumXDVZSSULn3x0r5iqJ0lUhZ2mxnfUkGEbpi7m3vT8cTI/gf8lthNGLEZ1aSgV7NfpesMVuMkzboLYPOQq0eZ/9UKvFmHfA2ccUAquAVK6x6hVrmYoGT3LXRQnjpeIx5C+sAY8ZtZg3z7+r74b0x1qLCr9bhvAMued0HR7W2YIxWXahEnfGZ4aUZRB+TkX6bU0FFOGB8VcmaVPBEuwW4YkI4XiA8OFHJWCkYGpHDYrPKO7LPDX+Xj/qbg+y4xfz8dQrjiILrTsddobuHaMUyJ8Io3EoLWMsuYVL4tGQp8J/CDF+cbFFnkXGlUnAh5mbjKGwayywSJYtAfP7LSWK3S1+de+O7NDctq8aKMko6/OfnbaUr29M0BmqLizZdD+kE3f4EIGs//UDmU1i6QQw/KyyFWd+OC09uU=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/The-Only-True-Mother-Goose-Melodies_4901
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy